#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
#  Amelie — Install into the system + configure sudo permissions
#  Usage: bash setup-system.sh
#         bash setup-system.sh /path/to/amelie.AppImage
#
#  Requires sudo ONCE to:
#    • install dependencies (wireguard-tools, cifs-utils, fuse, imagemagick, ghostscript)
#    • create the /etc/sudoers.d/amelie rule  (so it won't ask for a password afterwards)
#    • install the AppImage and the icons
# ─────────────────────────────────────────────────────────────────────────────

# ── Colors ────────────────────────────────────────────────────────────────────
R='\033[0;31m'   # red
G='\033[0;32m'   # green
Y='\033[1;33m'   # yellow
B='\033[0;34m'   # blue
C='\033[0;36m'   # cyan
W='\033[1;37m'   # bold white
D='\033[2m'      # dimmed
N='\033[0m'      # reset

hr() { printf "${D}%s${N}\n" "$(printf '─%.0s' {1..60})"; }

banner() {
  echo ""
  hr
  echo -e "${W}  Amelie — System install${N}"
  echo -e "${D}  Note app with encrypted vault + WireGuard/Samba sync${N}"
  hr
  echo ""
}

step() { echo -e "\n${B}[${1}/${TOTAL_STEPS}]${N} ${W}${2}${N}"; }
ok()   { echo -e "  ${G}✓${N}  ${1}"; }
warn() { echo -e "  ${Y}⚠${N}  ${1}"; }
fail() { echo -e "  ${R}✗${N}  ${1}"; }
run()  { echo -e "  ${D}\$ ${*}${N}"; "$@"; }
info() { echo -e "  ${D}${1}${N}"; }

TOTAL_STEPS=6
banner

# ── Find AppImage ─────────────────────────────────────────────────────────────
if [ -n "$1" ] && [ -f "$1" ]; then
  APPIMAGE=$(realpath "$1")
else
  APPIMAGE=$(ls dist/[Aa]melie-[0-9]*.AppImage 2>/dev/null | sort -V | tail -1)
  if [ -z "$APPIMAGE" ]; then
    fail "AppImage not found. Run first: bash scripts/install.sh"
    exit 1
  fi
  APPIMAGE=$(realpath "$APPIMAGE")
fi

USER_NAME=$(whoami)
info "AppImage : $APPIMAGE"
info "User     : $USER_NAME"
info "System   : $(grep ^NAME /etc/os-release 2>/dev/null | cut -d= -f2 | tr -d '"')"
echo ""

# ── Check sudo ────────────────────────────────────────────────────────────────
echo -e "${Y}This installation requires sudo to:${N}"
echo -e "  • Install wireguard-tools, cifs-utils, fuse"
echo -e "  • Create /etc/sudoers.d/amelie (wg-quick and mount permissions)"
echo ""
echo -e "${D}Enter your sudo password when prompted.${N}"
echo -e "${D}After this setup, Amelie will no longer ask for the password.${N}"
echo ""
sudo -v || { fail "sudo not available"; exit 1; }

# ── [1/6] System dependencies ─────────────────────────────────────────────────
step 1 "System dependencies"

if command -v dnf &>/dev/null; then
  DISTRO="fedora"
  echo -e "  ${D}Detected: Fedora / RHEL${N}"

  PKGS_NEEDED=()
  for pkg in wireguard-tools cifs-utils fuse fuse-libs imagemagick ghostscript; do
    if ! rpm -q "$pkg" &>/dev/null; then
      PKGS_NEEDED+=("$pkg")
    else
      ok "$pkg (already installed)"
    fi
  done

  if [ ${#PKGS_NEEDED[@]} -gt 0 ]; then
    echo -e "  ${Y}Installing: ${PKGS_NEEDED[*]}${N}"
    run sudo dnf install -y "${PKGS_NEEDED[@]}"
  fi

elif command -v apt-get &>/dev/null; then
  DISTRO="debian"
  echo -e "  ${D}Detected: Ubuntu / Debian${N}"

  PKGS_NEEDED=()
  for pkg in wireguard wireguard-tools cifs-utils libfuse2 fuse imagemagick ghostscript; do
    if ! dpkg -l "$pkg" &>/dev/null; then
      PKGS_NEEDED+=("$pkg")
    else
      ok "$pkg (already installed)"
    fi
  done

  if [ ${#PKGS_NEEDED[@]} -gt 0 ]; then
    echo -e "  ${Y}Installing: ${PKGS_NEEDED[*]}${N}"
    run sudo apt-get install -y "${PKGS_NEEDED[@]}"
  fi

elif command -v pacman &>/dev/null; then
  DISTRO="arch"
  echo -e "  ${D}Detected: Arch Linux${N}"
  run sudo pacman -Sy --noconfirm wireguard-tools cifs-utils fuse2 imagemagick ghostscript
fi

ok "Dependencies installed"

# ── [2/6] sudoers rule for Amelie ─────────────────────────────────────────────
step 2 "Configuring sudo permissions"

echo -e "  ${D}Amelie uses sudo for:${N}"

WG_QUICK=$(which wg-quick 2>/dev/null || echo "/usr/bin/wg-quick")
MOUNT_BIN=$(which mount 2>/dev/null || echo "/usr/bin/mount")
UMOUNT_BIN=$(which umount 2>/dev/null || echo "/usr/bin/umount")
MOUNT_DIR="$HOME/.local/share/amelie/mounts"

echo ""
echo -e "  ${C}wg-quick${N}     — bring the WireGuard tunnel up/down"
echo -e "  ${D}  \$ sudo wg-quick up ~/.amelie/wg-tunnel.conf${N}"
echo -e "  ${D}  \$ sudo wg-quick down ~/.amelie/wg-tunnel.conf${N}"
echo ""
echo -e "  ${C}mount.cifs${N}   — mount the remote Samba share"
echo -e "  ${D}  \$ sudo mount -t cifs //10.8.0.1/vault ~/.local/share/amelie/mounts/xxx${N}"
echo -e "  ${D}    -o username=user,password=•••,uid=$(id -u),vers=3.0${N}"
echo ""
echo -e "  ${C}umount${N}       — unmount after the sync"
echo -e "  ${D}  \$ sudo umount ~/.local/share/amelie/mounts/xxx${N}"
echo ""

SUDOERS_FILE="/etc/sudoers.d/amelie"
SUDOERS_CONTENT="# Amelie — permissions for WireGuard and Samba mount
# Generated by setup-system.sh on $(date '+%Y-%m-%d %H:%M')
$USER_NAME ALL=(ALL) NOPASSWD: $WG_QUICK
$USER_NAME ALL=(ALL) NOPASSWD: $MOUNT_BIN -t cifs *
$USER_NAME ALL=(ALL) NOPASSWD: $UMOUNT_BIN $MOUNT_DIR/*"

echo -e "  ${D}Writing $SUDOERS_FILE :${N}"
echo ""
echo -e "${D}┌─────────────────────────────────────────────────────────────┐${N}"
while IFS= read -r line; do
  printf "${D}│${N} %-61s ${D}│${N}\n" "$line"
done <<< "$SUDOERS_CONTENT"
echo -e "${D}└─────────────────────────────────────────────────────────────┘${N}"
echo ""

echo "$SUDOERS_CONTENT" | run sudo tee "$SUDOERS_FILE" > /dev/null
run sudo chmod 440 "$SUDOERS_FILE"

# Validate
if sudo visudo -c -f "$SUDOERS_FILE" &>/dev/null; then
  ok "sudoers rule valid → $SUDOERS_FILE"
else
  fail "Error in the sudoers rule — removing it for safety"
  sudo rm -f "$SUDOERS_FILE"
  exit 1
fi

# ── [3/6] Create Amelie folders ───────────────────────────────────────────────
step 3 "Amelie data folders"

for dir in \
  "$HOME/.amelie" \
  "$HOME/.local/bin" \
  "$HOME/.local/share/amelie/mounts" \
  "$HOME/.local/share/applications" \
  "$HOME/.local/share/icons/hicolor/256x256/apps" \
  "$HOME/.local/share/icons/hicolor/128x128/apps" \
  "$HOME/.local/share/icons/hicolor/64x64/apps" \
  "$HOME/.local/share/icons/hicolor/48x48/apps"; do
  mkdir -p "$dir"
  ok "$dir"
done

# ── [4/6] Install AppImage ────────────────────────────────────────────────────
step 4 "Install AppImage"

DEST="$HOME/.local/bin/amelie.AppImage"
run cp "$APPIMAGE" "$DEST"
run chmod +x "$DEST"
ok "Installed to $DEST"

# ── [5/6] Icons ───────────────────────────────────────────────────────────────
step 5 "Icons"

ICON_SRC="$(dirname "$0")/../assets/icon.png"
ICON_DIR="$HOME/.local/share/icons/hicolor"

if [ -f "$ICON_SRC" ]; then
  if command -v convert &>/dev/null; then
    for SIZE in 256 128 64 48; do
      TARGET="$ICON_DIR/${SIZE}x${SIZE}/apps/amelie.png"
      run convert "$ICON_SRC" -resize "${SIZE}x${SIZE}" "$TARGET" 2>/dev/null
      ok "Icon ${SIZE}×${SIZE}px"
    done
  else
    for SIZE in 256 128 64 48; do
      cp "$ICON_SRC" "$ICON_DIR/${SIZE}x${SIZE}/apps/amelie.png"
    done
    warn "ImageMagick not found — icons copied without resizing"
  fi
  mkdir -p "$ICON_DIR/scalable/apps"
  cp "$ICON_SRC" "$ICON_DIR/scalable/apps/amelie.png"
  gtk-update-icon-cache "$ICON_DIR" 2>/dev/null || true
  ok "Icon cache updated"
else
  warn "assets/icon.png not found — add your icon and re-run"
fi

# ── [6/6] .desktop file ───────────────────────────────────────────────────────
step 6 "Application shortcut (.desktop)"

DESKTOP_FILE="$HOME/.local/share/applications/amelie.desktop"

cat > "$DESKTOP_FILE" << DESKTOP
[Desktop Entry]
Version=1.0
Type=Application
Name=Amelie
Exec=$DEST --appimage-extract-and-run %U
Icon=amelie
Terminal=false
StartupNotify=true
Categories=Office;TextEditor;Utility;
Keywords=note;markdown;notes;vault;wireguard;
StartupWMClass=amelie
MimeType=text/markdown;
DESKTOP

chmod +x "$DESKTOP_FILE"

if command -v update-desktop-database &>/dev/null; then
  run update-desktop-database "$HOME/.local/share/applications" 2>/dev/null
  ok "Application database updated"
fi

ok "Shortcut created: search for 'Amelie' in the launcher"

# ── PATH check ────────────────────────────────────────────────────────────────
if ! echo "$PATH" | grep -q "$HOME/.local/bin"; then
  echo ""
  warn "~/.local/bin is not in your PATH. Add to ~/.bashrc or ~/.zshrc:"
  echo -e "  ${C}export PATH=\"\$HOME/.local/bin:\$PATH\"${N}"
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
hr
echo -e "${G}  ✓  Amelie installed successfully!${N}"
hr
echo ""
echo -e "${W}  Launch:${N}"
echo -e "  ${C}amelie.AppImage${N}           — from the terminal"
echo -e "  ${C}search 'Amelie' in the launcher${N} — GNOME / KDE"
echo ""
echo -e "${W}  Configured permissions:${N}"
echo -e "  ${D}sudo wg-quick up/down${N}      — no password"
echo -e "  ${D}sudo mount -t cifs${N}         — no password"
echo -e "  ${D}sudo umount${N}                — no password"
echo ""
echo -e "${W}  Data:${N}"
echo -e "  ${D}~/.amelie/${N}                 — config, salt, wg-tunnel.conf"
echo -e "  ${D}~/.local/share/amelie/${N}     — temporary sync mounts"
echo -e "  ${D}Your vault${N}                 — chosen on first launch"
echo ""
echo -e "${W}  Uninstall:${N}"
echo -e "  ${D}bash scripts/uninstall.sh${N}"
hr
echo ""

printf "Launch Amelie now? [y/N] "
read -r ans
[[ "$ans" =~ ^[yY]$ ]] && "$DEST" &
